<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

return
        [
            'CustomConfig' => [
                'Form.Template' => [
                    'button' => '<button{{attrs}} class="btn btn-default">{{text}}</button>',
                    'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
                    'checkboxFormGroup' => '<label>{{input}} {{label}}</label>',
                    'checkboxWrapper' => '<div class="checkbox">{{input}}{{label}}</div>',
                    'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
                    'error' => '<div class="help-block">{{content}}</div>',
                    'errorList' => '<ul>{{content}}</ul>',
                    'errorItem' => '<li>{{text}}</li>',
                    'file' => '<input type="file" name="{{name}}"{{attrs}}>',
                    'fieldset' => '<fieldset>{{content}}</fieldset>',
                    'formstart' => '<form{{attrs}}>',
                    'formend' => '</form>',
                    'formGroup' => '{{label}}{{input}}',
                    'hiddenblock' => '<div style="display:none;">{{content}}</div>',
                    'input' => '<input class="form-control" type="{{type}}" name="{{name}}"{{attrs}}>',
                    'inputSubmit' => '<input type="{{type}}"{{attrs}}>',
                    'inputContainer' => '<div class="form-group {{type}}{{required}}">{{content}}</div>',
                    'inputContainerError' => '<div class="form-group {{type}}{{required}} has-error">{{content}}{{error}}</div>',
                    'label' => '{{text}}',
                    'legend' => '<legend>{{text}}</legend>',
                    'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
                    'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
                    'select' => '<select class="form-control" name="{{name}}"{{attrs}}>{{content}}</select>',
                    'selectMultiple' => '<select class="form-control" name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
                    'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
                    'radioWrapper' => '<div class="radio"><label>{{input}} {{label}}</label></div>',
                    'textarea' => '<textarea class="form-control" name="{{name}}"{{attrs}}>{{value}}</textarea>',
                    'submitContainer' => '<div class="submit">{{content}}</div>'
				],
            
            'FormFilter.Template' => [
	            'button' => '<button{{attrs}} class="btn btn-default btn-sm">{{text}}</button>',
	            'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
	            'checkboxFormGroup' => '<label>{{input}} {{label}}</label>',
	            'checkboxWrapper' => '<div class="checkbox">{{input}}{{label}}</div>',
	            'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
	            'error' => '<div class="help-block">{{content}}</div>',
	            'errorList' => '<ul>{{content}}</ul>',
	            'errorItem' => '<li>{{text}}</li>',
	            'file' => '<input type="file" name="{{name}}"{{attrs}}>',
	            'fieldset' => '<fieldset>{{content}}</fieldset>',
	            'formstart' => '<form{{attrs}}>',
	            'formend' => '</form>',
	            'formGroup' => '{{label}}{{input}}',
	            'hiddenblock' => '<div style="display:none;">{{content}}</div>',
	            'input' => '<input class="form-control input-sm" type="{{type}}" name="{{name}}"{{attrs}}>',
	            'inputSubmit' => '<input type="{{type}}"{{attrs}}>',
	            'inputContainer' => '<div class="form-group col-md-3 {{type}}{{required}}">{{content}}</div>',
	            'inputContainerError' => '<div class="form-group col-md-3 {{type}}{{required}} has-error">{{content}}{{error}}</div>',
	            'label' => '{{text}}',
	            'legend' => '<legend>{{text}}</legend>',
	            'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
	            'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
	            'select' => '<select class="form-control input-sm" name="{{name}}"{{attrs}}>{{content}}</select>',
	            'selectMultiple' => '<select class="form-control" name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
	            'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
	            'radioWrapper' => '<div class="radio"><label>{{input}} {{label}}</label></div>',
	            'textarea' => '<textarea class="form-control" name="{{name}}"{{attrs}}>{{value}}</textarea>',
	            'submitContainer' => '<div class="submit" >{{content}}</div>'
			],
				'FormSave.Template' => [
				'button' => '<button{{attrs}} class="btn btn-default btn-sm">{{text}}</button>',
				'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
				'checkboxFormGroup' => '<label>{{input}} {{label}}</label>',
				'checkboxWrapper' => '<div class="checkbox">{{input}}{{label}}</div>',
				'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
				'error' => '<div class="help-block">{{content}}</div>',
				'errorList' => '<ul>{{content}}</ul>',
				'errorItem' => '<li>{{text}}</li>',
				'file' => '<input type="file" name="{{name}}"{{attrs}}>',
				'fieldset' => '<fieldset>{{content}}</fieldset>',
				'formstart' => '<form{{attrs}}>',
				'formend' => '</form>',
				'formGroup' => '{{label}}{{input}}',
				'hiddenblock' => '<div style="display:none;">{{content}}</div>',
				'input' => '<input class="form-control input-sm" type="{{type}}" name="{{name}}"{{attrs}}>',
				'inputSubmit' => '<input type="{{type}}"{{attrs}}>',
				'inputContainer' => '<div class="form-group col-md-4 {{type}}{{required}}">{{content}}</div>',
				'inputContainerError' => '<div class="form-group col-md-4 {{type}}{{required}} has-error">{{content}}{{error}}</div>',
				'label' => '{{text}}',
				'legend' => '<legend>{{text}}</legend>',
				'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
				'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
				'select' => '<select class="form-control" name="{{name}}"{{attrs}}>{{content}}</select>',
				'selectMultiple' => '<select class="form-control" name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
				'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
				'radioWrapper' => '<div class="radio"><label>{{input}} {{label}}</label></div>',
				'textarea' => '<textarea class="form-control" name="{{name}}"{{attrs}}>{{value}}</textarea>',
				'submitContainer' => '<div class="submit" >{{content}}</div>'
			],
			
			'FormH.Template' => [
			/*
			'button' => '<button{{attrs}} class="btn btn-default btn-sm">{{text}}</button>',
			'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
			//'checkboxFormGroup' => '<label>{{input}} {{label}}</label>',
			'checkboxWrapper' => '<div class="checkbox">{{input}}{{label}}</div>',
			'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
			'error' => '<div class="help-block">{{content}}</div>',
			'errorList' => '<ul>{{content}}</ul>',
			'errorItem' => '<li>{{text}}</li>',
			'file' => '<input type="file" name="{{name}}"{{attrs}}>',
			'fieldset' => '<fieldset>{{content}}</fieldset>',
			'formstart' => '<form{{attrs}}>',
			'formend' => '</form>',
			//'formGroup' => '{{label}}{{input}}',
			'hiddenblock' => '<div style="display:none;">{{content}}</div>',
			'input' => '<div class="col-md-5"> <input class="form-control input-sm" type="{{type}}" name="{{name}}"{{attrs}}> </div>',
			'inputSubmit' => '<input type="{{type}}"{{attrs}}>',
			//'inputContainer' => '<div class="form-group {{type}}{{required}}">{{content}}</div>',
			'inputContainerError' => '<div class="form-group  {{type}}{{required}} has-error">{{content}}{{error}}</div>',
			//'label' => '<label class="col-sm-2 control-label">{{text}}</label>',
			'legend' => '<legend>{{text}}</legend>',
			'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
			'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
			'select' => '<select class="form-control " name="{{name}}"{{attrs}}>{{content}}</select>',
			'selectMultiple' => '<select class="form-control" name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
			'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
			'radioWrapper' => '<div class="radio"><label>{{input}} {{label}}</label></div>',
			'textarea' => '<textarea class="form-control" name="{{name}}"{{attrs}}>{{value}}</textarea>',
			//'submitContainer' => '<div class="submit" >{{content}}</div>',
			*/
			'dateWidget' => '<span class="form-inline">{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}</span>',
			'error' => '<div class="text-danger">{{content}}</div>',
			
			'input' => '<div class="col-md-5"> <input class="form-control input-sm" type="{{type}}" name="{{name}}"{{attrs}}> </div>',
			'checkboxWrapper' => '<div class="checkbox"><label>{{input}}{{label}}</label></div>',
			'radioWrapper' => '<div class="radio"><label>{{input}}{{label}}</label></div>',
			'label' => '<label class="control-label col-md-2"{{attrs}}>{{text}}</label>',
			'formGroup' => '{{label}}<div class=" col-md-10">{{input}}{{error}}{{help}}</div>',
			'checkboxFormGroup' => '<div class=""><div class="checkbox">{{label}}</div>{{error}}{{help}}</div>',
			'submitContainer' => '<div class="col-md-10 col-md-offset-2">{{content}}</div>',
			'inputContainer' => '<div class="form-group {{type}}{{required}} {{col}}">{{content}}</div>',
			'inputContainerError' => '<div class="form-group {{type}}{{required}} has-error">{{content}}</div>',
			]
		]
];
